name: fr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.2
  - h5py=3.7.0
  - pyyaml=6.0
  - pip=23.0.1
  - matplotlib=3.7.1
  - pip:
      - dm-haiku==0.0.9
      - jax==0.4.8
      - jaxlib==0.4.7+cuda11.cudnn86
      - ml-collections==0.1.1
      - optax==0.1.4
      - wandb==0.14.0

