name: fr
channels:
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7.0
  - cudnn=8.4.1.50
  - h5py=3.7.0
  - ipykernel=6.21
  - ipython
  - matplotlib=3.7.1
  - numpy=1.23.5
  - jaxlib=0.4.2=*cuda*
  - jax=0.4.4
  - jupyter_client
  - jupyter_core
  - optax=0.1.4
  - python=3.10.9
  - pip=23.0.1
  - pip:
      - dm-haiku==0.0.9
      - gitpython
      - pyyaml
      - wandb
      - ml-collections=0.1.1
