name: fr
channels:
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7.0
  - cudnn=8.4.1.50
  - h5py=3.7.0
  - hdf5=1.10.6
  - ipykernel=6.9.1
  - ipython=8.4.0
  - jax=0.4.1
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.2
  - nccl=2.14.3.1
  - numpy=1.23.4
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - optax=0.1.4
  - python=3.9.13
  - scipy=1.9.3
  - pip=23.0.1
  - pip:
      - dm-haiku==0.0.9
      - gitpython==3.1.29
      - pip==23.0.1
      - pyyaml==6.0
      - wandb==0.13.5
